### ISSUE TITLE
Avoiding "check_expand_need" call

### ISSUE THREAD

**Issue by simoatze** [emilk/emilib#1]
Hi Emil,

thanks a lot for sharing your hash_set table, it's extremely fast!
I have just a question, the insert function calls the `check_expand_need` function before inserting.
In my case I need a fixed size set of 25000 items and I call the reserve function at the beginning of my program, so I was wondering if I could actually avoid the call `check_expand_need`, since I know there won't be more than 25000 items.
I tried to remove that call and for some reason the program hangs, but I can't figure out why, do you have any idea why this happens?

Thanks!

**Comment by emilk** [comment]
I can't think of a reason, except for you filling up the HashSet (i.e. adding more elements than you reserved space for).

Btw, if you know your elements are all unique (no duplicates), you can use the faster `insert_unque` function (it still calls check_expand_need, though).

**Comment by simoatze** [comment]
Emil, yes that was the reason, I didn't reserve enough space. Reserving the right space I was able to avoid the call to `check_expand_need `.

Thanks!
Simone
